# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20160922_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(help_text='English Building Name', max_length=30),
        ),
    ]
