# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20160927_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Country'),
        ),
    ]
