# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_remove_property_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
