# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_delete_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='property',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='company',
        ),
        migrations.RemoveField(
            model_name='floor',
            name='property',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='property',
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Floor',
        ),
        migrations.DeleteModel(
            name='Lease',
        ),
    ]
