# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Country'),
        ),
    ]
