# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_property_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(max_length=1024),
        ),
    ]
