# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20160928_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('floor', models.IntegerField()),
                ('avilable', models.DateTimeField(blank=True, null=True)),
                ('createdon', models.DateTimeField(default=django.utils.timezone.now)),
                ('modifiedon', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Property')),
            ],
        ),
    ]
