# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_auto_20160928_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='createdby',
        ),
        migrations.RemoveField(
            model_name='property',
            name='modifiedby',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='createdby',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='modifiedby',
        ),
        migrations.AlterField(
            model_name='property',
            name='createdon',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='createdon',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
