# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_auto_20160929_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
