# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.Property'),
        ),
    ]
