# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 08:52
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_auto_20160929_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_body',
            field=models.ImageField(upload_to='', verbose_name=django.core.files.storage.FileSystemStorage(location='/media/photos')),
        ),
    ]
